version: "3"
services:
  go-docker-image:  #Нужно создать образ go-docker-image
    build: ./       #Образ должен быть собран с использованием Dockerfile в директории ./
    ports:          #Сопоставляем порты
      - '80:80'
    volumes:
      - ./:/app     #Устанавливаем директорию хоста в директорию /app контейнера Docker